create type "public"."wit_category" as enum ('win', 'wit', 'wipeout');

create table "public"."wit_comments" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "comment" text not null,
    "user_id" uuid,
    "wit_id" bigint
);


alter table "public"."wit_comments" enable row level security;

create table "public"."wits" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text,
    "content" text,
    "reference" text,
    "user_id" uuid,
    "tags" text[],
    "category" wit_category not null
);


alter table "public"."wits" enable row level security;

CREATE UNIQUE INDEX wit_comments_pkey ON public.wit_comments USING btree (id);

CREATE UNIQUE INDEX wits_pkey ON public.wits USING btree (id);

alter table "public"."wit_comments" add constraint "wit_comments_pkey" PRIMARY KEY using index "wit_comments_pkey";

alter table "public"."wits" add constraint "wits_pkey" PRIMARY KEY using index "wits_pkey";

alter table "public"."wit_comments" add constraint "public_wit_comments_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE SET NULL not valid;

alter table "public"."wit_comments" validate constraint "public_wit_comments_user_id_fkey";

alter table "public"."wit_comments" add constraint "public_wit_comments_wit_id_fkey" FOREIGN KEY (wit_id) REFERENCES wits(id) ON DELETE CASCADE not valid;

alter table "public"."wit_comments" validate constraint "public_wit_comments_wit_id_fkey";

alter table "public"."wits" add constraint "public_wits_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(id) not valid;

alter table "public"."wits" validate constraint "public_wits_user_id_fkey";

grant delete on table "public"."wit_comments" to "anon";

grant insert on table "public"."wit_comments" to "anon";

grant references on table "public"."wit_comments" to "anon";

grant select on table "public"."wit_comments" to "anon";

grant trigger on table "public"."wit_comments" to "anon";

grant truncate on table "public"."wit_comments" to "anon";

grant update on table "public"."wit_comments" to "anon";

grant delete on table "public"."wit_comments" to "authenticated";

grant insert on table "public"."wit_comments" to "authenticated";

grant references on table "public"."wit_comments" to "authenticated";

grant select on table "public"."wit_comments" to "authenticated";

grant trigger on table "public"."wit_comments" to "authenticated";

grant truncate on table "public"."wit_comments" to "authenticated";

grant update on table "public"."wit_comments" to "authenticated";

grant delete on table "public"."wit_comments" to "service_role";

grant insert on table "public"."wit_comments" to "service_role";

grant references on table "public"."wit_comments" to "service_role";

grant select on table "public"."wit_comments" to "service_role";

grant trigger on table "public"."wit_comments" to "service_role";

grant truncate on table "public"."wit_comments" to "service_role";

grant update on table "public"."wit_comments" to "service_role";

grant delete on table "public"."wits" to "anon";

grant insert on table "public"."wits" to "anon";

grant references on table "public"."wits" to "anon";

grant select on table "public"."wits" to "anon";

grant trigger on table "public"."wits" to "anon";

grant truncate on table "public"."wits" to "anon";

grant update on table "public"."wits" to "anon";

grant delete on table "public"."wits" to "authenticated";

grant insert on table "public"."wits" to "authenticated";

grant references on table "public"."wits" to "authenticated";

grant select on table "public"."wits" to "authenticated";

grant trigger on table "public"."wits" to "authenticated";

grant truncate on table "public"."wits" to "authenticated";

grant update on table "public"."wits" to "authenticated";

grant delete on table "public"."wits" to "service_role";

grant insert on table "public"."wits" to "service_role";

grant references on table "public"."wits" to "service_role";

grant select on table "public"."wits" to "service_role";

grant trigger on table "public"."wits" to "service_role";

grant truncate on table "public"."wits" to "service_role";

grant update on table "public"."wits" to "service_role";


